# Generated by Django 5.1.6 on 2025-02-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasker_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
